//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HydroColor.Resources.Strings {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("HydroColor.Resources.Strings.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The methodology used by HydroColor is similar to that used with precision radiometers. HydroColor uses three images collected by the user to: (1) measure how much light is emanating from the water&apos;s surface, (2) correct that value for sun/sky glint off the surface, and (3) normalize it by the total incoming radiation. This provides a nearly illumination independent measure of the amount light reflected out of the water..
        /// </summary>
        internal static string About_HowDoesHydroColorWorkBody {
            get {
                return ResourceManager.GetString("About_HowDoesHydroColorWorkBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How Does HydroColor Work?.
        /// </summary>
        internal static string About_HowDoesHydroColorWorkTitle {
            get {
                return ResourceManager.GetString("About_HowDoesHydroColorWorkTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HydroColor requires that you have a photographers 18% reflectance gray card and access to deep unshaded water. HydroColor will guide you through the collection of three images. The images are processed onboard the phone to provide values of reflectance and water turbidity. The data can be viewed in the app or emailed via the Library tab..
        /// </summary>
        internal static string About_HowToUseHydroColorBody {
            get {
                return ResourceManager.GetString("About_HowToUseHydroColorBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How to Use HydroColor.
        /// </summary>
        internal static string About_HowToUseHydroColorTitle {
            get {
                return ResourceManager.GetString("About_HowToUseHydroColorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A Water Quality App.
        /// </summary>
        internal static string About_HydroColorSubtitle {
            get {
                return ResourceManager.GetString("About_HydroColorSubtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HydroColor:.
        /// </summary>
        internal static string About_HydroColorTitle {
            get {
                return ResourceManager.GetString("About_HydroColorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click here to view the introduction screen again, which explains the basics of the measurement..
        /// </summary>
        internal static string About_IntroScreenLink {
            get {
                return ResourceManager.GetString("About_IntroScreenLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HydroColor was developed by Thomas Leeuw and Emmanuel Boss at the University of Maine. To learn more about HydroColor, see the following links. HydroColor has been improved to use RAW camera data since the 2018 publication below..
        /// </summary>
        internal static string About_LearnMore {
            get {
                return ResourceManager.GetString("About_LearnMore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        internal static string AppShell_AboutTabTitle {
            get {
                return ResourceManager.GetString("AppShell_AboutTabTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Collect Data.
        /// </summary>
        internal static string AppShell_CollectDataTabTitle {
            get {
                return ResourceManager.GetString("AppShell_CollectDataTabTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Library.
        /// </summary>
        internal static string AppShell_LibraryTabTitle {
            get {
                return ResourceManager.GetString("AppShell_LibraryTabTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string CameraController_NoCameraDismissButton {
            get {
                return ResourceManager.GetString("CameraController_NoCameraDismissButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No compatible cameras were found on the device. If the device has a camera, it may not support raw image capture..
        /// </summary>
        internal static string CameraController_NoCameraMessage {
            get {
                return ResourceManager.GetString("CameraController_NoCameraMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Camera.
        /// </summary>
        internal static string CameraController_NoCameraTitle {
            get {
                return ResourceManager.GetString("CameraController_NoCameraTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Capture.
        /// </summary>
        internal static string CaptureImage_CaptureButton {
            get {
                return ResourceManager.GetString("CaptureImage_CaptureButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compass Not Working?.
        /// </summary>
        internal static string CaptureImage_CompassNotWorkingLink {
            get {
                return ResourceManager.GetString("CaptureImage_CompassNotWorkingLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Processing Image....
        /// </summary>
        internal static string CaptureImage_ImageProcessingInProgress {
            get {
                return ResourceManager.GetString("CaptureImage_ImageProcessingInProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string CaptureImage_NoCompassDismissButton {
            get {
                return ResourceManager.GetString("CaptureImage_NoCompassDismissButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The current device does not have a magnetic compass..
        /// </summary>
        internal static string CaptureImage_NoCompassMessage {
            get {
                return ResourceManager.GetString("CaptureImage_NoCompassMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compass Not Supported.
        /// </summary>
        internal static string CaptureImage_NoCompassTitle {
            get {
                return ResourceManager.GetString("CaptureImage_NoCompassTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No GPS coordinates, HydroColor cannot determine the correct heading for the images. Either enter GPS coordinates or capture all images approximately 45 degrees from your shadow..
        /// </summary>
        internal static string CaptureImage_NoGPSNoHeadingHelp {
            get {
                return ResourceManager.GetString("CaptureImage_NoGPSNoHeadingHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string CaptureImage_NoOrientationDismissButton {
            get {
                return ResourceManager.GetString("CaptureImage_NoOrientationDismissButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The current device does not have an orientation sensor..
        /// </summary>
        internal static string CaptureImage_NoOrientationMessage {
            get {
                return ResourceManager.GetString("CaptureImage_NoOrientationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Orientation Not Supported.
        /// </summary>
        internal static string CaptureImage_NoOrientationTitle {
            get {
                return ResourceManager.GetString("CaptureImage_NoOrientationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Analyze Images.
        /// </summary>
        internal static string CollectData_AnalyzeImagesButton {
            get {
                return ResourceManager.GetString("CollectData_AnalyzeImagesButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aquiring Location ....
        /// </summary>
        internal static string CollectData_AquiringLocationInProgress {
            get {
                return ResourceManager.GetString("CollectData_AquiringLocationInProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter in decimal degrees, negative is South..
        /// </summary>
        internal static string CollectData_EnterLatitudeMessage {
            get {
                return ResourceManager.GetString("CollectData_EnterLatitudeMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Latitude.
        /// </summary>
        internal static string CollectData_EnterLatitudeTitle {
            get {
                return ResourceManager.GetString("CollectData_EnterLatitudeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter in decimal degrees, negative is West..
        /// </summary>
        internal static string CollectData_EnterLongitudeMessage {
            get {
                return ResourceManager.GetString("CollectData_EnterLongitudeMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Longitude.
        /// </summary>
        internal static string CollectData_EnterLongitudeTitle {
            get {
                return ResourceManager.GetString("CollectData_EnterLongitudeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string CollectData_GPSNotSupportedDismissButton {
            get {
                return ResourceManager.GetString("CollectData_GPSNotSupportedDismissButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The current device does not support GPS location..
        /// </summary>
        internal static string CollectData_GPSNotSupportedMessage {
            get {
                return ResourceManager.GetString("CollectData_GPSNotSupportedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GPS Not Supported.
        /// </summary>
        internal static string CollectData_GPSNotSupportedTitle {
            get {
                return ResourceManager.GetString("CollectData_GPSNotSupportedTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gray Card.
        /// </summary>
        internal static string CollectData_GrayCardDisplayName {
            get {
                return ResourceManager.GetString("CollectData_GrayCardDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string CollectData_IncompleteImagesDismissButton {
            get {
                return ResourceManager.GetString("CollectData_IncompleteImagesDismissButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must collect a Gray Card, Sky, and Water image before continuing..
        /// </summary>
        internal static string CollectData_IncompleteImagesMessage {
            get {
                return ResourceManager.GetString("CollectData_IncompleteImagesMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incomplete Images.
        /// </summary>
        internal static string CollectData_IncompleteImagesTitle {
            get {
                return ResourceManager.GetString("CollectData_IncompleteImagesTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lat:.
        /// </summary>
        internal static string CollectData_LatitudeAbbreviation {
            get {
                return ResourceManager.GetString("CollectData_LatitudeAbbreviation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location Accuracy:.
        /// </summary>
        internal static string CollectData_LocationAccuracy {
            get {
                return ResourceManager.GetString("CollectData_LocationAccuracy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string CollectData_LocationPermissionDeniedDismissButton {
            get {
                return ResourceManager.GetString("CollectData_LocationPermissionDeniedDismissButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The HydroColor app uses GPS location to determine the optimal direction for image capture. Please enable location access for the HydroColor app in the system settings..
        /// </summary>
        internal static string CollectData_LocationPermissionDeniedMessage {
            get {
                return ResourceManager.GetString("CollectData_LocationPermissionDeniedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location Permission Denied.
        /// </summary>
        internal static string CollectData_LocationPermissionDeniedTitle {
            get {
                return ResourceManager.GetString("CollectData_LocationPermissionDeniedTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lon:.
        /// </summary>
        internal static string CollectData_LongitudeAbbreviation {
            get {
                return ResourceManager.GetString("CollectData_LongitudeAbbreviation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leave blank to continue without naming..
        /// </summary>
        internal static string CollectData_MeasurementNameMessage {
            get {
                return ResourceManager.GetString("CollectData_MeasurementNameMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Measurement Name.
        /// </summary>
        internal static string CollectData_MeasurementNameTitle {
            get {
                return ResourceManager.GetString("CollectData_MeasurementNameTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string CollectData_NoGPSDismissButton {
            get {
                return ResourceManager.GetString("CollectData_NoGPSDismissButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HydroColor was unable to determine your GPS position. Retry or enter your Lat/Lon coordinates manually..
        /// </summary>
        internal static string CollectData_NoGPSMessage {
            get {
                return ResourceManager.GetString("CollectData_NoGPSMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No GPS.
        /// </summary>
        internal static string CollectData_NoGPSTitle {
            get {
                return ResourceManager.GetString("CollectData_NoGPSTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh Location.
        /// </summary>
        internal static string CollectData_RefreshLocationButton {
            get {
                return ResourceManager.GetString("CollectData_RefreshLocationButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sky.
        /// </summary>
        internal static string CollectData_SkyDisplayName {
            get {
                return ResourceManager.GetString("CollectData_SkyDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Now is not an ideal time for HydroColor measurments. Tap here to see why..
        /// </summary>
        internal static string CollectData_SunElevationWarningBanner {
            get {
                return ResourceManager.GetString("CollectData_SunElevationWarningBanner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string CollectData_SunElevationWarningDismissButton {
            get {
                return ResourceManager.GetString("CollectData_SunElevationWarningDismissButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The best time for HydroColor measurements is when the sun is between 20 and 85 degrees above the horizon.\n\nThe sun elevation based on the phones current location and time is.
        /// </summary>
        internal static string CollectData_SunElevationWarningMessage_1 {
            get {
                return ResourceManager.GetString("CollectData_SunElevationWarningMessage_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to degrees..
        /// </summary>
        internal static string CollectData_SunElevationWarningMessage_2 {
            get {
                return ResourceManager.GetString("CollectData_SunElevationWarningMessage_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sun Elevation.
        /// </summary>
        internal static string CollectData_SunElevationWarningTitle {
            get {
                return ResourceManager.GetString("CollectData_SunElevationWarningTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Water.
        /// </summary>
        internal static string CollectData_WaterDisplayName {
            get {
                return ResourceManager.GetString("CollectData_WaterDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string CompassCalibrationHelp_DismissButton {
            get {
                return ResourceManager.GetString("CompassCalibrationHelp_DismissButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If the compass is not working as you expect, the phones internal compass sensor may require calibration.
        ///                
        ///The calibration procedure is simple. With the compass open on the screen (in HydroColor or Maps app), wave the phone in a figure 8 pattern ensuring you invert the phone as part of the pattern..
        /// </summary>
        internal static string CompassCalibrationHelp_HelpMessage {
            get {
                return ResourceManager.GetString("CompassCalibrationHelp_HelpMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tap here to see a video on how to calibrate the compass..
        /// </summary>
        internal static string CompassCalibrationHelp_HelpVideoLink {
            get {
                return ResourceManager.GetString("CompassCalibrationHelp_HelpVideoLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compass Calibration.
        /// </summary>
        internal static string CompassCalibrationHelp_Title {
            get {
                return ResourceManager.GetString("CompassCalibrationHelp_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gray Card.
        /// </summary>
        internal static string Data_GrayCard {
            get {
                return ResourceManager.GetString("Data_GrayCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blue.
        /// </summary>
        internal static string Data_ReflectanceGraphBlueLabel {
            get {
                return ResourceManager.GetString("Data_ReflectanceGraphBlueLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Green.
        /// </summary>
        internal static string Data_ReflectanceGraphGreenLabel {
            get {
                return ResourceManager.GetString("Data_ReflectanceGraphGreenLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Red.
        /// </summary>
        internal static string Data_ReflectanceGraphRedLabel {
            get {
                return ResourceManager.GetString("Data_ReflectanceGraphRedLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reflectance.
        /// </summary>
        internal static string Data_ReflectanceGraphYAxisLabel {
            get {
                return ResourceManager.GetString("Data_ReflectanceGraphYAxisLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sky.
        /// </summary>
        internal static string Data_Sky {
            get {
                return ResourceManager.GetString("Data_Sky", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Red:.
        /// </summary>
        internal static string Data_TableBackscatterRedLabel {
            get {
                return ResourceManager.GetString("Data_TableBackscatterRedLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1/m.
        /// </summary>
        internal static string Data_TableBackscatterRedUnits {
            get {
                return ResourceManager.GetString("Data_TableBackscatterRedUnits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date:.
        /// </summary>
        internal static string Data_TableDateLabel {
            get {
                return ResourceManager.GetString("Data_TableDateLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lat:.
        /// </summary>
        internal static string Data_TableLatitudeLabel {
            get {
                return ResourceManager.GetString("Data_TableLatitudeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deg..
        /// </summary>
        internal static string Data_TableLatitudeUnits {
            get {
                return ResourceManager.GetString("Data_TableLatitudeUnits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lon:.
        /// </summary>
        internal static string Data_TableLongitudeLabel {
            get {
                return ResourceManager.GetString("Data_TableLongitudeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deg..
        /// </summary>
        internal static string Data_TableLongitudeUnits {
            get {
                return ResourceManager.GetString("Data_TableLongitudeUnits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reflec Blue:.
        /// </summary>
        internal static string Data_TableReflectanceBlueLabel {
            get {
                return ResourceManager.GetString("Data_TableReflectanceBlueLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reflec Green:.
        /// </summary>
        internal static string Data_TableReflectanceGreenLabel {
            get {
                return ResourceManager.GetString("Data_TableReflectanceGreenLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reflec Red:.
        /// </summary>
        internal static string Data_TableReflectanceRedLabel {
            get {
                return ResourceManager.GetString("Data_TableReflectanceRedLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1/sr.
        /// </summary>
        internal static string Data_TableReflectanceUnits {
            get {
                return ResourceManager.GetString("Data_TableReflectanceUnits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SPM:.
        /// </summary>
        internal static string Data_TableSuspendedParticulateMatterLabel {
            get {
                return ResourceManager.GetString("Data_TableSuspendedParticulateMatterLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mg/L.
        /// </summary>
        internal static string Data_TableSuspendedParticulateMatterUnits {
            get {
                return ResourceManager.GetString("Data_TableSuspendedParticulateMatterUnits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time:.
        /// </summary>
        internal static string Data_TableTimeLabel {
            get {
                return ResourceManager.GetString("Data_TableTimeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Local.
        /// </summary>
        internal static string Data_TableTimeUnits {
            get {
                return ResourceManager.GetString("Data_TableTimeUnits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Turbidity:.
        /// </summary>
        internal static string Data_TableTurbidityLabel {
            get {
                return ResourceManager.GetString("Data_TableTurbidityLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NTU.
        /// </summary>
        internal static string Data_TableTurbidityUnits {
            get {
                return ResourceManager.GetString("Data_TableTurbidityUnits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Water.
        /// </summary>
        internal static string Data_Water {
            get {
                return ResourceManager.GetString("Data_Water", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to + Add Email Address.
        /// </summary>
        internal static string FileReaderWriter_AddEmail {
            get {
                return ResourceManager.GetString("FileReaderWriter_AddEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address will be saved..
        /// </summary>
        internal static string FileReaderWriter_AddEmailMessage {
            get {
                return ResourceManager.GetString("FileReaderWriter_AddEmailMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Email.
        /// </summary>
        internal static string FileReaderWriter_AddEmailTitle {
            get {
                return ResourceManager.GetString("FileReaderWriter_AddEmailTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string FileReaderWriter_ConfirmDeleteEmailCancelButton {
            get {
                return ResourceManager.GetString("FileReaderWriter_ConfirmDeleteEmailCancelButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string FileReaderWriter_ConfirmDeleteEmailDeleteButton {
            get {
                return ResourceManager.GetString("FileReaderWriter_ConfirmDeleteEmailDeleteButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete The Following Address:.
        /// </summary>
        internal static string FileReaderWriter_ConfirmDeleteEmailMessage {
            get {
                return ResourceManager.GetString("FileReaderWriter_ConfirmDeleteEmailMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm Delete.
        /// </summary>
        internal static string FileReaderWriter_ConfirmDeleteEmailTitle {
            get {
                return ResourceManager.GetString("FileReaderWriter_ConfirmDeleteEmailTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send HydroColor Data File To:.
        /// </summary>
        internal static string FileReaderWriter_ConfirmSendEmailMessage_1 {
            get {
                return ResourceManager.GetString("FileReaderWriter_ConfirmSendEmailMessage_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter custom data file suffix (optional):.
        /// </summary>
        internal static string FileReaderWriter_ConfirmSendEmailMessage_2 {
            get {
                return ResourceManager.GetString("FileReaderWriter_ConfirmSendEmailMessage_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string FileReaderWriter_ConfirmSendEmailMessageCancelButton {
            get {
                return ResourceManager.GetString("FileReaderWriter_ConfirmSendEmailMessageCancelButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send.
        /// </summary>
        internal static string FileReaderWriter_ConfirmSendEmailMessageSendButton {
            get {
                return ResourceManager.GetString("FileReaderWriter_ConfirmSendEmailMessageSendButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm Email.
        /// </summary>
        internal static string FileReaderWriter_ConfirmSendEmailTitle {
            get {
                return ResourceManager.GetString("FileReaderWriter_ConfirmSendEmailTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to - Delete Email Address.
        /// </summary>
        internal static string FileReaderWriter_DeleteEmail {
            get {
                return ResourceManager.GetString("FileReaderWriter_DeleteEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string FileReaderWriter_DeleteEmailCancelButton {
            get {
                return ResourceManager.GetString("FileReaderWriter_DeleteEmailCancelButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Address to DELETE.
        /// </summary>
        internal static string FileReaderWriter_DeleteEmailMessage {
            get {
                return ResourceManager.GetString("FileReaderWriter_DeleteEmailMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string FileReaderWriter_EmailFailedDismissButton {
            get {
                return ResourceManager.GetString("FileReaderWriter_EmailFailedDismissButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to send email. The data file can be manually downloaded by connecting the phone to a computer and navigating to: Phone\\Android\\data\\com.h2optics.hydrocolor\\files\\.
        /// </summary>
        internal static string FileReaderWriter_EmailFailedMessageAndroid {
            get {
                return ResourceManager.GetString("FileReaderWriter_EmailFailedMessageAndroid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to send email. The data file can be manually downloaded by connecting the phone to a computer with Itunes, than navigating to the ‘File Sharing’ tab of Itunes..
        /// </summary>
        internal static string FileReaderWriter_EmailFailedMessageIOS {
            get {
                return ResourceManager.GetString("FileReaderWriter_EmailFailedMessageIOS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email Failed.
        /// </summary>
        internal static string FileReaderWriter_EmailFailedTitle {
            get {
                return ResourceManager.GetString("FileReaderWriter_EmailFailedTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string FileReaderWriter_EmailSentDismissButton {
            get {
                return ResourceManager.GetString("FileReaderWriter_EmailSentDismissButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HydroColor Data File Sent To:.
        /// </summary>
        internal static string FileReaderWriter_EmailSentMessage_1 {
            get {
                return ResourceManager.GetString("FileReaderWriter_EmailSentMessage_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It may appear in your junk mail folder..
        /// </summary>
        internal static string FileReaderWriter_EmailSentMessage_2 {
            get {
                return ResourceManager.GetString("FileReaderWriter_EmailSentMessage_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email Sent.
        /// </summary>
        internal static string FileReaderWriter_EmailSentTitle {
            get {
                return ResourceManager.GetString("FileReaderWriter_EmailSentTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string FileReaderWriter_SelectEmailCancelButton {
            get {
                return ResourceManager.GetString("FileReaderWriter_SelectEmailCancelButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Address to Send Data File.
        /// </summary>
        internal static string FileReaderWriter_SelectEmailMessage {
            get {
                return ResourceManager.GetString("FileReaderWriter_SelectEmailMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string HardwarePermissions_CameraPermissionDismissButton {
            get {
                return ResourceManager.GetString("HardwarePermissions_CameraPermissionDismissButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The HydroColor app requires access to the camera to collect a series of images used in the measurement. Please enable camera access for the HydroColor app in the system settings..
        /// </summary>
        internal static string HardwarePermissions_CameraPermissionMessage {
            get {
                return ResourceManager.GetString("HardwarePermissions_CameraPermissionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Camera Permission.
        /// </summary>
        internal static string HardwarePermissions_CameraPermissionTitle {
            get {
                return ResourceManager.GetString("HardwarePermissions_CameraPermissionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string Library_DeleteButton {
            get {
                return ResourceManager.GetString("Library_DeleteButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string Library_DeleteMeasurementCancelButton {
            get {
                return ResourceManager.GetString("Library_DeleteMeasurementCancelButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string Library_DeleteMeasurementDeleteButton {
            get {
                return ResourceManager.GetString("Library_DeleteMeasurementDeleteButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm Deletion.
        /// </summary>
        internal static string Library_DeleteMeasurementTitle {
            get {
                return ResourceManager.GetString("Library_DeleteMeasurementTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit List.
        /// </summary>
        internal static string Library_EditListButton {
            get {
                return ResourceManager.GetString("Library_EditListButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Done.
        /// </summary>
        internal static string Library_EditListDoneButton {
            get {
                return ResourceManager.GetString("Library_EditListDoneButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email Data File....
        /// </summary>
        internal static string Library_EmailDataFileButton {
            get {
                return ResourceManager.GetString("Library_EmailDataFileButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing Measurements?.
        /// </summary>
        internal static string Library_MissingMeasurementsLink {
            get {
                return ResourceManager.GetString("Library_MissingMeasurementsLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string Library_MissingMeasurmentsDismissButtion {
            get {
                return ResourceManager.GetString("Library_MissingMeasurmentsDismissButtion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HydroColor version 2.0 was a major update to how the app collects and stores data. Measurements collected with HydroColor versions before 2.0 are no longer viewable in the app. Don’t panic! The data file containing all your measurements is still available on your device. \n\nYou can download the datafile containing your past measurements by connecting your Android phone to a computer. The HydroColor data files are available under &lt;your phone&gt;\\Android\\data\\com.h2optics.hydrocolor\\files\\..
        /// </summary>
        internal static string Library_MissingMeasurmentsMessageAndroid {
            get {
                return ResourceManager.GetString("Library_MissingMeasurmentsMessageAndroid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HydroColor version 2.0 was a major update to how the app collects and stores data. Measurements collected with HydroColor versions before 2.0 are no longer viewable in the app. Don’t panic! The data file containing all your measurements is still available on your device. \n\nYou can download the datafile containing your past measurements by connecting your iPhone to a computer. On Mac, the HydroColor data files are available under the ‘Files’ tab. On a PC, you must connect the iPhone with iTunes, then the d [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Library_MissingMeasurmentsMessageIOS {
            get {
                return ResourceManager.GetString("Library_MissingMeasurmentsMessageIOS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing Data.
        /// </summary>
        internal static string Library_MissingMeasurmentsTitle {
            get {
                return ResourceManager.GetString("Library_MissingMeasurmentsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Measurements to Display.
        /// </summary>
        internal static string Library_NoMeasurements {
            get {
                return ResourceManager.GetString("Library_NoMeasurements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        internal static string Welcome_BackButton {
            get {
                return ResourceManager.GetString("Welcome_BackButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HydroColor requires the collection of a gray card, water, and sky image to compute the reflectance. HydroColor uses the center of each image, show by a square over the camera preview. Ensure the area inside the square is uniformly filled with the gray card, sky, or water.\n\nThe gray card must be held level or placed on level surface before taking the gray card picture. Avoid imaging shadows on the gray card or debris on the water surface..
        /// </summary>
        internal static string Welcome_CollectingImagesBody {
            get {
                return ResourceManager.GetString("Welcome_CollectingImagesBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Collecting Images.
        /// </summary>
        internal static string Welcome_CollectingImagesTitle {
            get {
                return ResourceManager.GetString("Welcome_CollectingImagesTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Don&apos;t Show Intro Again.
        /// </summary>
        internal static string Welcome_DontShowIntroAgainCheckbox {
            get {
                return ResourceManager.GetString("Welcome_DontShowIntroAgainCheckbox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Each image is taken at a specific angle to minimize surface reflection.\n\nA compass and tilt display will guide you to the correct image angles. Line up the green arrows on both displays before capturing an image..
        /// </summary>
        internal static string Welcome_ImageAnglesBody {
            get {
                return ResourceManager.GetString("Welcome_ImageAnglesBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image Angles.
        /// </summary>
        internal static string Welcome_ImageAnglesTitle {
            get {
                return ResourceManager.GetString("Welcome_ImageAnglesTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can learn more about HydroColor at the following links:.
        /// </summary>
        internal static string Welcome_LearnMoreBody {
            get {
                return ResourceManager.GetString("Welcome_LearnMoreBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Learn More.
        /// </summary>
        internal static string Welcome_LearnMoreTitle {
            get {
                return ResourceManager.GetString("Welcome_LearnMoreTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next.
        /// </summary>
        internal static string Welcome_NextButton {
            get {
                return ResourceManager.GetString("Welcome_NextButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start.
        /// </summary>
        internal static string Welcome_StartButton {
            get {
                return ResourceManager.GetString("Welcome_StartButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HydroColor is a tool for measuring the reflectance (or simply color) of natural water bodies. The measured reflectance can be used to infer various properties of the water. \n\nHydroColor provides reflectance measurements in the red, green, and blue color channels of the camera. Additionally, water turbidity is derived from the reflectance in the red channel..
        /// </summary>
        internal static string Welcome_WelcomeToHydroColorBody {
            get {
                return ResourceManager.GetString("Welcome_WelcomeToHydroColorBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome to HydroColor.
        /// </summary>
        internal static string Welcome_WelcomeToHydroColorTitle {
            get {
                return ResourceManager.GetString("Welcome_WelcomeToHydroColorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HydroColor requires a photographers 18% reflectance gray card. These are fairly standardized and only cost a few dollars. However, you must ensure the card is specified as 18% reflectance. \n\nYou will need access to deep unshaded water. If the bottom is visible, it is too shallow to use HydroColor. Docks and piers are usually the best place to perform HydroColor measurements..
        /// </summary>
        internal static string Welcome_WhatsNeededBody {
            get {
                return ResourceManager.GetString("Welcome_WhatsNeededBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What’s Needed?.
        /// </summary>
        internal static string Welcome_WhatsNeededTitle {
            get {
                return ResourceManager.GetString("Welcome_WhatsNeededTitle", resourceCulture);
            }
        }
    }
}
